### ISSUE TITLE
Add Text animation in the title "QUIZ" in quiz.html file

### ISSUE THREAD

**Issue by Castella1313** [Castella1313/PYCHAMP#4]
Add Text animation in the title "QUIZ" in quiz.html file

**Comment by ArdhenisAflah** [comment]
ok

**Comment by Castella1313** [comment]
@sayaPintar haha what okay??

**Comment by ArdhenisAflah** [comment]
nothing just boring

Pada tanggal 3 Okt 2020 23.33, "Simran-bhardwaj" <notifications@github.com>
menulis:

@sayaPintar <https://github.com/sayaPintar> haha what okay??

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Castella1313/PYCHAMP/issues/4#issuecomment-703129620>,
or unsubscribe

**Comment by symtalha14** [comment]
Hello, I would like to work on it. Please assign me this issue so that I can make a valid PR.

**Comment by Samridhi-98** [comment]
I would like to contribute please assign me.

**Comment by Abhi-4793** [comment]
I worked on it and added a animation .can you assign me this issue so i can make a PR.

**Comment by Castella1313** [comment]
@symtalha14 it would be great if you can make a pr by tomorrow, on 5th i will assign to the other contributor in the queue

**Comment by Castella1313** [comment]
@Samridhi-98 added to queue
@Abhi-4793 added to queue

**Comment by symtalha14** [comment]
> @symtalha14 it would be great if you can make a pr by tomorrow, on 5th i will assign to the other contributor in the queue

I'm On It, will initiate a Pull Request very soon.

**Comment by Abhi-4793** [comment]
i already made the changes for animation and its working if you assign me i make a PR now.

**Comment by symtalha14** [comment]
Please review my PR.

**Comment by symtalha14** [comment]
Just a suggestion: If you wish that your repository participates in the Hacktober fest, You need to add the label "hacktoberfest" instead of "Hacktoberfest". :)
